---
title: "DNAメタバーコーディングによるムクドリの食性調査を通した都市生態系の解析"
author: "加藤千尋"
format: html
editor: visual
---

## 第1章　研究背景・目的

## 第2章　材料と方法

### 2.1　サンプリング

　本研究では、千葉県北西部の3地点にてムクドリ *Sturnus cineraceus* の排泄物のサンプリングを行った。

### 2.1.1　津田沼

　2023年7月6日19時から20時半に、津田沼公園の樹下にて排泄物を採取した。ムクドリが集まっている樹木を目視にて確認し、その下にビニール傘を設置して落下する排泄物を受け止めてサンプリングを行った。

### 2.1.2　千葉

　2023年7月10日19時から20時半に、葭川公園駅そばの樹下にて排泄物を採取した。ムクドリが集まっている樹木を目視にて確認し、その下にビニール傘を設置して落下する排泄物を受け止めてサンプリングを行った。

### 2.1.3　新松戸

　2023年7月20日19時から20時半に、レッドロブスター新松戸店前にて排泄物を採取した。ムクドリが集まっている樹木を目視にて確認し、その下にビニール傘を設置して落下する排泄物を受け止めてサンプリングを行った。

### 2.1.4　サンプリングした排泄物の処理

　サンプリングした排泄物は、冷凍庫にて冷凍保管を行った。

　鳥の排泄物に含まれている尿酸にはDNA抽出を阻害する効果があることが指摘されている(Ericsson,2017)。そのため、DNA抽出を行う前にサンプリングした排泄物について白く見える尿酸を取り除く作業を行った。

### 2.2　DNA抽出

　QIAamp DNA Stoolキットのプロトコルを元に、DNA抽出を行った。

1.  2mlのマイクロ遠心チューブに4mmジルコニアビーズ3粒を入れ、事前に破砕したサンプルを180mg～220mg入れた。温度上昇でDNAが分解されるのを避けるため、サンプルはできる限り氷上で扱った。
2.  Inhibit Buffer 1.0mlを各サンプルに加え、転倒混和した。サンプルとInhibit Bufferが完全に混ざるまで、ボルテックスを用いて最高速度で1分間攪拌した。
3.  2.の液を70℃のウォーターバスで5分間インキュベートした。その際、チューブに水が入らないようパラフィルムで覆った。
4.  3.でインキュベートしたチューブを最高速度で1分間遠心し、糞便サンプルの粒子をペレット化させた。
5.  新しい1.5mlマイクロ遠心チューブにproteinase K 15μlを加えた。
6.  4.の上澄み液 200μlを5.のチューブに加えた。
7.  6.にBuffer AL 200μlを加え、15秒間ボルテックスで攪拌した。
8.  7.のチューブを55℃のウォーターバスで3時間インキュベートした。インキュベート中も、時々転倒混和を行った。
9.  8.のチューブに99.5% ethanol 200μlを加え、ボルテックスで攪拌した。
10. 2mlコレクションチューブにQIAamp spin columnをセットし、QIAamp spin columnの縁を濡らさないように9.のチューブの内容液600μlを垂らした。QIAamp spin columnのキャップを閉めて最高速度で1分間遠心した。遠心後、内容液がQIAamp spin columnの上に残っていた場合は、QIAamp spin columnが空になるまで追加で遠心を行った。QIAamp spin columnを新しい2mlコレクションチューブに移し、ろ液の入っているチューブは廃棄した。
11. QIAamp spin columnのキャップを慎重に開け、Buffer AW1 500μlを加えた。キャップを閉めて最高速度で1分間遠心した。QIAamp spin columnを新しい2mlコレクションチューブに移し、ろ液の入っているチューブは廃棄した。
12. QIAamp spin columnのキャップを慎重に開け、Buffer AW2 500μlを加えた。キャップを閉めて最高速度で3分間遠心した。QIAamp spin columnを新しい2mlコレクションチューブに移し、ろ液の入っているチューブは廃棄した。
13. 12.のコレクションチューブを最高速度で3分間遠心し、Buffer AW2の残りを完全に除去した。
14. 新しい1.5mlマイクロ遠心チューブにラベリングし、13.のQIAamp spin columnを移した。QIAamp spin columnのキャップを慎重に開けてBuffer ATE 100μlを加え、室温で1分間置いたのち最高速度で1分間遠心操作を行ってDNAを溶出した。
15. QubitとNanodropを用いてDNAの濃度と純度を測定した。得られたDNA溶液は-30℃で冷凍保管した。

### 2.3　PCR増幅

　2.2で抽出したDNAのPCR増幅を行った。ムクドリは雑食性であるため、動物食用の増幅プライマーとしてZBJ-Artを、植物食用の増幅プライマーとしてtrnLを使用した。

### 2.3.1　1stPCR

　1stPCRでは、PCR組成液として2X Master Mix6.0μl、10μM 1st primers F0.24μl、10μM 1st primers R0.24μl、Template DNA1.0μl、滅菌超純水2.52μlの合計10μlを0.2mlチューブに入れた。温度条件は、95℃15分、94℃30秒、57℃90℃、72℃1分、72℃10分で行った。94℃30秒、57℃90℃、72℃1分の部分は35サイクル行った。

　1stPCR後、得られた1stPCR産物を用いて電気泳動を行い、バンドが100-600bpに出ていることを確認したのち、生物技研へ発送した。

| 1stPCR反応組成     | 液量   |
|:-------------------|:-------|
| 2X Master Mix      | 6.0μl  |
| 10μM 1st primers F | 0.24μl |
| 10μM 1st primers R | 0.24μl |
| Template DNA       | 1.0μl  |
| 滅菌超純水         | 2.52μl |
| total              | 10μl   |

使用したprimerの配列は次の通りである。

| プライマー名 | 塩基配列                                       |
|:-------------|:-----------------------------------------------|
| ZBJ-ArtF1c   | 5'-GATATTGGAACWTTATATTTTATTTTTGG-3' (Tm=60-63) |
| ZBJ-ArtR2c   | 5'-WACTAATCAATTWCCAAATCCTCC- 3' (Tm=61-67)     |
| trnL-c       | 5'-CGAAATCGGTAGACGCTACG-3' (Tm=64.4)           |
| trnL-h       | 5'-CCATTGAGTCTCTGCACCTATC-3' (Tm=62.54)        |

### 2.3.2　2ndPCR

　2ndPCRは株式会社生物技研に委託した。

　まず、1stPCR産物に1.0×PCR溶液量のVAHTS DNA Clean Beads (Vazyme)を添加し、PCR産物を精製した。

　次に、Synergy H1 (Agilent Technologies)とQuantiFluor dsDNA System (Promega)を用いて、精製した溶液の濃度測定を行った。

　2ndPCRでは、PCR組成液として2× PCR Buffer for KOD FX Neo 5.0μl、dNTPs(each 2 mM) 2.0μl、5μM Forward primer 0.5μl、5μM Reverse primer 0.5μl、PCR product 1.0μl、KOD FX Neo (1.0 U/uL)\[TOYOBO\] 0.2μl、Nuclease-Free Water 0.8μlの合計10μlを0.2mlチューブに入れた。温度条件は、94℃2分、98℃10秒、60℃30秒、68℃30秒、68℃2分で行う。98℃10秒、60℃30秒、68℃30秒の部分は10サイクル行った。

| 2ndPCR反応組成                  | 液量  |
|:--------------------------------|:------|
| 2× PCR Buffer for KOD FX Neo    | 5.0μl |
| dNTPs(each 2 mM)                | 2.0μl |
| 5μM Forward primer              | 0.5μl |
| 5μM Reverse primer              | 0.5μl |
| PCR product                     | 1.0μl |
| KOD FX Neo (1.0 U/uL)\[TOYOBO\] | 0.2μl |
| Nuclease-Free Water             | 0.8μl |
| total                           | 10μl  |

使用したprimerの配列は次の通りである。

| プライマー名 | 塩基配列                                                           |
|:---------------|:-------------------------------------------------------|
| 2ndF         | 5'-AATGATACGGCGACCACCGAGATCTACAC-Index2- ACACTCTTTCCCTACACGACGC-3' |
| 2ndR         | 5'-CAAGCAGAAGACGGCATACGAGAT-Index1- GTGACTGGAGTTCAGACGTGTG- 3'     |

### 2.4　DNAシーケンス・塩基配列決定・種同定

　DNAシーケンス及び塩基配列決定、機械的な種同定は株式会社生物技研に委託した。

1.  プライマー配列に一致したリードの抽出\
    FASTX-Toolkit (ver. 0.0.14)のfastx_barcode_splitter toolを用いて得られたリード配列の読み始めが使用したプライマー配列と完全に一致するリード配列のみを抽出した。 抽出したリードからプライマー配列と3'端の50塩基をFASTX-Toolkitのfastx_trimmerで削除した。その後、sickle (ver. 1.33)を用いて品質値が20未満の配列を取り除き、40塩基以下の長さとなった配列とそのペア配列を破棄した。
2.  リードの結合\
    ペアエンドリード結合スクリプトFLASH (ver. 1.2.11)を用いて、最小の重なりを10塩基の条件でリードを結合した。
3.  Qiime2を用いた解析\
    Qiime2 (ver. 2023.7)のdada2プラグインでキメラ配列とノイズ配列を除去した後、代表配列とASV表を出力した。取得した代表配列をNCBIのntに対し、BLASTN (ver. 2.13.0)を行い、系統推定を行った。その他のパラメーターは標準の条件で行った。
4.  オリジナル解析\
    Qiime2のtools exportプラグインでqzv形式のデータを閲覧可能なデータに変換した後、生物技研オリジナルプログラムによって閲覧しやすいデータに加工した(株式会社生物技研、2023)。　

## 第3章　実験結果及び考察

## 付録
